name: mlproperties
favicon: null
layout_spectrum: 0.9423613054677844
typography_spectrum: 0.8437359461095184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7966394326649606
  lightness: 0.48651755903847516
  saturation: 0.016650056466460228
  rhythmicContrast: 0.28537650336511433
purpose: []
